# Generated by Django 5.1.5 on 2025-01-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('employed_date', models.DateField()),
            ],
        ),
    ]
